# Other packages you may want to install:
#
#  * zsh-autosuggestions
#  * zsh-completions
#  * zsh-syntax-highlighting
#

typeset -r zdot_dir="$([[ -z ${ZDOTDIR+x} ]] && echo "$HOME" || echo "$ZDOTDIR")"

# Lines configured by zsh-newuser-install
HISTFILE=~/.local/state/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
unsetopt beep

bindkey -v

# Set <Esc> delay to 0.01s. See zshparam(1).
export KEYTIMEOUT=1

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
# zstyle :compinstall filename '/home/pdigiglio/.zshrc'
zstyle :compinstall filename '$zdot_dir/.zshrc'

# Arrow-driven completion
zstyle ':completion:*' menu select

# Case-insensitive path completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

autoload -Uz compinit

# Add my custom completions. Do this before calling compinit.
fpath=("$zdot_dir/completions" $fpath)
compinit
# End of lines added by compinstall

# -- Prompt

# - Enable VCS information
# See:

# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '(%F{yellow}%b%f) '

# Set up the prompt (with git branch name)
setopt PROMPT_SUBST
# -

# PROMPT='%F{#c0c0c0}%n%f@%F{#008000}%m%f %F{#800080}%B%~%b%f %# '
# PROMPT='%F{#c0c0c0}%n%f@%F{#008000}%m%f %F{#800080}%B%~%b%f (${vcs_info_msg_0_}) %# '
PROMPT='%F{#009070}%~%f ${vcs_info_msg_0_}%# '
RPROMPT='[%F{yellow}%?%f]'

# -- Allow '#' to comment lines in interactive shell.
setopt INTERACTIVE_COMMENTS

# --


. "$zdot_dir/aliases.sh"
. "$zdot_dir/env.sh"
. "$zdot_dir/gpg.sh"

. "$zdot_dir/run_help.sh"
. "$zdot_dir/syntax_highlighting.sh"
. "$zdot_dir/autosuggestions.sh"
